spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driverspring.datasource.jdbc-url=jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:com.example.boardserver.mapper/*.xml
  data:
    redis:
      host: localhost
      port: 6379
      password: test1234
      repository:
        enabled: false
expire:
  defaultTime: 3600

